### ISSUE TITLE
Make eigenmixture database

### ISSUE THREAD

**Issue by eshaanjoshi** [Linalg-Class/facial-recognition#7]
Create an eigen mixture for images that have been transformed.

**Comment by AleksBekker** [comment]
# What this part entails

For this "database," all we need is a way to store a person's ID, name, and eigenmixture (up to a certain rank). This will involve two tables: one to relate the ID and the name and another to relate the ID to the picture (we don't want to store people's names in the same database for security reasons).

So, please create two map objects (https://www.mathworks.com/help/matlab/map-containers.html)

- [ ] Map 1: `personal`
    - Keys: Random ID numbers
    - Values: peoples' names
- [ ] Map 2: `eigenweights`
    - Keys: Random ID numbers (MUST BE THE SAME AS IN MAP 1)
    - Values: The vector of the person's eigenvectors up to some rank r

Additionally, please make the following functions:
- [ ] `createNewEntry(personalMap, eigenweightsMap, newName, newEigenweights)`
    - Generates a **UNIQUE** key to be used in both maps
    - Adds `newName` and `newEigenweights` to their respective map

**Comment by KwameBuadu** [comment]
Ok, so here's what I did so far(Sorry if I wrote a bunch of nonsense)

![Screen Shot 2022-01-26 at 11 09 06 AM](https://user-images.githubusercontent.com/98181563/151221469-e5663ffb-b3cc-4beb-9150-a1d43fe0d0e8.png)
![Screen Shot 2022-01-26 at 11 09 20 AM](https://user-images.githubusercontent.com/98181563/151221497-abfa0959-3968-4b8e-a007-72a299ab2952.png)
![Screen Shot 2022-01-26 at 11 10 03 AM](https://user-images.githubusercontent.com/98181563/151221611-e5c2d33c-eb7e-4476-9217-357c37ba44eb.png)
![Screen Shot 2022-01-26 at 11 10 13 AM](https://user-images.githubusercontent.com/98181563/151221629-b418e28e-2b2a-49e1-a11f-a96847281a14.png)
:

**Comment by AleksBekker** [comment]
@KwameBuadu This is awesome! Could you submit a Pull Request (ask Eshaan or Rahul) so that I can take a look at it? Thank you!

**Comment by KwameBuadu** [comment]
You mean upload the file?

**Comment by AleksBekker** [comment]
Yeah, basically. Can you talk to one of them right now?

**Comment by KwameBuadu** [comment]
Yes

**Comment by KwameBuadu** [comment]
I think they'll take care of it. They're kinda busy atm and are not in a place to do it rn
