### ISSUE TITLE
Create algorithm to identify key features on images

### ISSUE THREAD

**Issue by eshaanjoshi** [Linalg-Class/facial-recognition#8]
Key features algorithm will basically be what we did in class

**Comment by AleksBekker** [comment]
This issue involves you writing several functions:
- [ ] `create_random_sample(dataset, column_count)`
  - Parameter `dataset`: a dataset that looks like our Yale B dataset (you can even use that dataset for testing)
  - Parameter `column_count`: an integer that represents a number of columns in the dataset
  - Returns: a new matrix that contains `column_count` columns from `dataset`. if `column_count` is greater than the number of columns in `dataset` or if it's equal to -1, return the entire dataset.

- [ ] `find_average_column(dataset)`
  - Parameter `dataset`: a dataset that looks like our Yale B dataset (you can even use that dataset for testing)
  - Returns: `mean(dataset, 2)`

- [ ] `find_eigenfaces(dataset)`
  - Parameter `dataset`: a dataset that looks like our Yale B dataset (you can even use that dataset for testing). Probably not mean-centered
  - Returns: the matrix of eigenfaces. **Make sure you mean center `dataset` before running the SVD**
